In [1]:
import os
import pandas as pd
from pathlib import Path

In [2]:
data_path = Path("../../data/processed/herd_mentality_events_processed_final.csv").resolve()
processed_path = Path("../../data/gold_layer/herd_mentality_events_gold_data_v1.csv").resolve()

In [3]:
df = pd.read_csv(data_path)
df

,Year,Event Name,Continent,Event Description,Country,Decade,Event Type,Trigger,M,S,I,D,R
0,1925,South African Rand mine strike,Africa,"In 1925, thousands of African gold‑mine worker...",South Africa,1920's,Social,Repression,8.0,4.0,7.0,5.0,8.0
1,1926,Birth of Pan-African Congress,Africa,"In 1926, African intellectuals and diaspora le...",United Kingdom,1920's,Social,Policy,6.0,9.0,5.0,3.0,9.0
2,1927,Foundation of ANC Youth League (SA),Africa,"In 1927, young activists in South Africa found...",South Africa,1920's,Social,Repression,4.0,6.0,6.0,4.0,7.0
3,1928,South African Black political conference,Africa,"In 1928, black political leaders from across S...",South Africa,1920's,Social,Repression,5.0,6.0,3.0,3.0,7.0
4,1930,Mass migration for economic reasons in Sahel,Africa,In 1930 a severe drought combined with the glo...,Mali,1930's,Social,Policy,7.0,8.0,8.0,6.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,2021,Papua volcano eruption response,Australia/Oceania,"In December 2021, Mount Manam in Papua New Gui...",Papua New Guinea,2020's,Social,Fear,6.0,6.0,7.0,5.0,7.0
621,2022,Fiji cyclone mass evacuations,Australia/Oceania,"In February 2022, Fiji’s Meteorological Servic...",Fiji,2020's,Social,Fear,5.0,6.0,7.0,5.0,5.0
622,2023,Indigenous Voice to Parliament activism (Austr...,Australia/Oceania,"Throughout 2023, Australia saw a nationwide su...",Australia,2020's,Social,Policy,6.0,6.0,6.0,8.0,4.0
623,2024,Pacific Islands anti-mining protests,Australia/Oceania,"In 2024, island communities across the Pacific...",Fiji,2020's,Social,Fear,6.0,8.0,7.0,5.0,7.0
624,2025,Brisbane Olympics preparations mass gatherings,Australia/Oceania,"In 2025, Brisbane, Queensland, became the foca...",Australia,2020's,Social,Hype,6.0,5.0,6.0,4.0,6.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               625 non-null    int64
 1   Event Name         625 non-null    object
 2   Continent          625 non-null    object
 3   Event Description  625 non-null    object
 4   Country            625 non-null    object
 5   Decade             625 non-null    object
 6   Event Type         625 non-null    object
 7   Trigger            625 non-null    object
 8   M                  625 non-null    float64
 9   S                  625 non-null    float64
 10  I                  625 non-null    float64
 11  D                  625 non-null    float64
 12  R                  625 non-null    float64
dtypes: float64(5), int64(1), object(7)
memory usage: 63.6+ KB

In [5]:
df.describe()

              Year           M           S           I           D           R
count   625.000000  625.000000  625.000000  625.000000  625.000000  625.000000
mean   1975.270400    6.820800    6.249600    6.764800    5.404800    7.512000
std      28.899564    1.187495    1.361715    1.121201    2.199426    1.143656
min    1925.000000    2.000000    3.000000    3.000000    1.000000    3.000000
25%    1950.000000    6.000000    6.000000    6.000000    4.000000    7.000000
50%    1975.000000    7.000000    6.000000    7.000000    5.000000    8.000000
75%    2000.000000    8.000000    6.000000    7.000000    7.000000    8.000000
max    2025.000000    9.000000   10.000000   10.000000   10.000000   10.000000

In [6]:
df = df.rename(columns={"M": "Magnitude(M)", "S": "Spread(S)", "I": "Intensity(I)", "D": "Duration(D)", "R": "Outcome/Impact(R)"})
df

,Year,Event Name,Continent,Event Description,Country,Decade,Event Type,Trigger,Magnitude(M),Spread(S),Intensity(I),Duration(D),Outcome/Impact(R)
0,1925,South African Rand mine strike,Africa,"In 1925, thousands of African gold‑mine worker...",South Africa,1920's,Social,Repression,8.0,4.0,7.0,5.0,8.0
1,1926,Birth of Pan-African Congress,Africa,"In 1926, African intellectuals and diaspora le...",United Kingdom,1920's,Social,Policy,6.0,9.0,5.0,3.0,9.0
2,1927,Foundation of ANC Youth League (SA),Africa,"In 1927, young activists in South Africa found...",South Africa,1920's,Social,Repression,4.0,6.0,6.0,4.0,7.0
3,1928,South African Black political conference,Africa,"In 1928, black political leaders from across S...",South Africa,1920's,Social,Repression,5.0,6.0,3.0,3.0,7.0
4,1930,Mass migration for economic reasons in Sahel,Africa,In 1930 a severe drought combined with the glo...,Mali,1930's,Social,Policy,7.0,8.0,8.0,6.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,2021,Papua volcano eruption response,Australia/Oceania,"In December 2021, Mount Manam in Papua New Gui...",Papua New Guinea,2020's,Social,Fear,6.0,6.0,7.0,5.0,7.0
621,2022,Fiji cyclone mass evacuations,Australia/Oceania,"In February 2022, Fiji’s Meteorological Servic...",Fiji,2020's,Social,Fear,5.0,6.0,7.0,5.0,5.0
622,2023,Indigenous Voice to Parliament activism (Austr...,Australia/Oceania,"Throughout 2023, Australia saw a nationwide su...",Australia,2020's,Social,Policy,6.0,6.0,6.0,8.0,4.0
623,2024,Pacific Islands anti-mining protests,Australia/Oceania,"In 2024, island communities across the Pacific...",Fiji,2020's,Social,Fear,6.0,8.0,7.0,5.0,7.0
624,2025,Brisbane Olympics preparations mass gatherings,Australia/Oceania,"In 2025, Brisbane, Queensland, became the foca...",Australia,2020's,Social,Hype,6.0,5.0,6.0,4.0,6.0

In [7]:
magnitude_value_map = {
    "1.0": "Minimal",
    "2.0": "Very Low",
    "3.0": "Low",
    "4.0": "Moderate-Low",
    "5.0": "Moderate",
    "6.0": "Moderate-High",
    "7.0": "High",
    "8.0": "Very High",
    "9.0": "Extreme",
    "10.0": "Historic"
}

spread_value_map = {
    "1.0": "Local",
    "2.0": "Multi-Local",
    "3.0": "City-Level",
    "4.0": "Regional",
    "5.0": "Multi-Regional",
    "6.0": "National",
    "7.0": "Bi-National",
    "8.0": "Multi-National",
    "9.0": "Continental",
    "10.0": "Global"
}

intensity_value_map = {
    "1.0": "Minimal",
    "2.0": "Very Low",
    "3.0": "Low",
    "4.0": "Moderate-Low",
    "5.0": "Moderate",
    "6.0": "Moderate-High",
    "7.0": "High",
    "8.0": "Very High",
    "9.0": "Critical",
    "10.0": "Maximum"
}

duration_value_map = {
    "1.0": "Momentary",
    "2.0": "Very Short",
    "3.0": "Short",
    "4.0": "Moderate-Short",
    "5.0": "Moderate",
    "6.0": "Long",
    "7.0": "Extended",
    "8.0": "Very Long",
    "9.0": "Multi-Year",
    "10.0": "Prolonged"
}

outcome_value_map = {
    "1.0": "Negligible",
    "2.0": "Very Low",
    "3.0": "Low",
    "4.0": "Moderate-Low",
    "5.0": "Moderate",
    "6.0": "Strong",
    "7.0": "Significant",
    "8.0": "Major",
    "9.0": "Transformational",
    "10.0": "Historic"
}

# Convert float64 values to strings before mapping (to match dictionary string keys)
df['Magnitude_label'] = df['Magnitude(M)'].astype(str).map(magnitude_value_map)
df['Spread_label'] = df['Spread(S)'].astype(str).map(spread_value_map)
df['Intensity_label'] = df['Intensity(I)'].astype(str).map(intensity_value_map)
df['Duration_label'] = df['Duration(D)'].astype(str).map(duration_value_map)
df['Outcome_label'] = df['Outcome/Impact(R)'].astype(str).map(outcome_value_map)
df

,Year,Event Name,Continent,Event Description,Country,Decade,Event Type,Trigger,Magnitude(M),Spread(S),Intensity(I),Duration(D),Outcome/Impact(R),Magnitude_label,Spread_label,Intensity_label,Duration_label,Outcome_label
0,1925,South African Rand mine strike,Africa,"In 1925, thousands of African gold‑mine worker...",South Africa,1920's,Social,Repression,8.0,4.0,7.0,5.0,8.0,Very High,Regional,High,Moderate,Major
1,1926,Birth of Pan-African Congress,Africa,"In 1926, African intellectuals and diaspora le...",United Kingdom,1920's,Social,Policy,6.0,9.0,5.0,3.0,9.0,Moderate-High,Continental,Moderate,Short,Transformational
2,1927,Foundation of ANC Youth League (SA),Africa,"In 1927, young activists in South Africa found...",South Africa,1920's,Social,Repression,4.0,6.0,6.0,4.0,7.0,Moderate-Low,National,Moderate-High,Moderate-Short,Significant
3,1928,South African Black political conference,Africa,"In 1928, black political leaders from across S...",South Africa,1920's,Social,Repression,5.0,6.0,3.0,3.0,7.0,Moderate,National,Low,Short,Significant
4,1930,Mass migration for economic reasons in Sahel,Africa,In 1930 a severe drought combined with the glo...,Mali,1930's,Social,Policy,7.0,8.0,8.0,6.0,7.0,High,Multi-National,Very High,Long,Significant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,2021,Papua volcano eruption response,Australia/Oceania,"In December 2021, Mount Manam in Papua New Gui...",Papua New Guinea,2020's,Social,Fear,6.0,6.0,7.0,5.0,7.0,Moderate-High,National,High,Moderate,Significant
621,2022,Fiji cyclone mass evacuations,Australia/Oceania,"In February 2022, Fiji’s Meteorological Servic...",Fiji,2020's,Social,Fear,5.0,6.0,7.0,5.0,5.0,Moderate,National,High,Moderate,Moderate
622,2023,Indigenous Voice to Parliament activism (Austr...,Australia/Oceania,"Throughout 2023, Australia saw a nationwide su...",Australia,2020's,Social,Policy,6.0,6.0,6.0,8.0,4.0,Moderate-High,National,Moderate-High,Very Long,Moderate-Low
623,2024,Pacific Islands anti-mining protests,Australia/Oceania,"In 2024, island communities across the Pacific...",Fiji,2020's,Social,Fear,6.0,8.0,7.0,5.0,7.0,Moderate-High,Multi-National,High,Moderate,Significant
624,2025,Brisbane Olympics preparations mass gatherings,Australia/Oceania,"In 2025, Brisbane, Queensland, became the foca...",Australia,2020's,Social,Hype,6.0,5.0,6.0,4.0,6.0,Moderate-High,Multi-Regional,Moderate-High,Moderate-Short,Strong

In [8]:
df.to_csv(processed_path, index=False)